name: flutter_project_template
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  card_loading: ^0.3.2
  http: ^1.2.0
  dio: ^5.4.0
  intl: ^0.19.0
  sqflite: ^2.3.2
  path: ^1.8.3
  top_snackbar_flutter: ^3.1.0
  material_dialogs: ^1.1.4
  lottie: ^2.7.0
  intro_screen_onboarding_flutter: ^1.0.0
  web_socket_channel: ^2.4.0
  bottom_bar: ^2.0.3
  flutter_slider_drawer: ^2.1.3
  smooth_page_indicator: ^1.1.0
  page_transition: "^2.0.9"
  flutter_svg: ^2.0.10+1
  image_picker: ^0.8.4+4
  responsive_sizer: ^3.3.1
  rename_app: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
